name: C/C++ CI

on:
  push:
  pull_request:

jobs:
  job_build_cpp:
    name: ${{ matrix.os }}-${{ matrix.buildConfig }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, ubuntu-22.04]
        include:
          - os: windows-2022
            buildConfig: release
            displayName: grad_prism_windows
            triplet: x64-windows-static
            configuration: 'x64.*'
            installPath: 'install/bin/'
          - os: ubuntu-22.04
            buildConfig: release
            displayName: grad_prism_ubuntu
            triplet: x64-linux
            configuration: 'x64.*'
            installPath: 'install/lib/'

    steps:

    # Checkout
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0

    # Install latest CMake
    - uses: lukka/get-cmake@latest

    # Setup vcpkg and build deps
    - name: Restore artifacts, or Run vcpkg, build and cache artifacts
      uses: lukka/run-vcpkg@v5
      id: runvcpkg
      with:
        #setupOnly: true
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        vcpkgTriplet: '${{ matrix.triplet }}'
        vcpkgArguments: 'prometheus-cpp boost-algorithm boost-property-tree fmt'
        vcpkgGitCommitId: '93b38546e271ac8047a6dd00469f14845beb4642'

    # Build with CMake and Ninja
    - name: Run CMake+Ninja
      uses: lukka/run-cmake@v3
      id: runcmake
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        buildWithCMakeArgs: ' -- install -v'
        buildDirectory: '${{ runner.workspace }}/b/ninja/'
        cmakeAppendedArgs: '-G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install'
        useVcpkgToolchainFile: true
        buildWithCMake: true

    # Build the mod
    - uses: gruppe-adler/action-release-with-hemtt@60f7195e5240289fecd07c29cc5ec8fd92ad2159
      name: 'Build Mod with HEMTT'
      id: build

    # Upload the mod
    - uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.displayName }}
        path: ${{ steps.build.outputs.release_path }}

  job_release:
    runs-on: windows-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    needs: [job_build_cpp]
    steps:
      # Download the build mod
      - name: Download windows build
        uses: actions/download-artifact@v2
        with:
          name: grad_prism_windows
      - name: Download ubuntu build
        uses: actions/download-artifact@v2
        with:
          name: grad_prism_ubuntu

      # zip it
      - uses: papeloto/action-zip@v1
        with:
          files: \@grad_prism/
          dest: \@grad_prism.zip

      # release it
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            \@grad_prism.zip
